# Generated by Django 5.1.6 on 2025-02-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('number_of_beds', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=15)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('proof_name', models.CharField(max_length=255)),
                ('proof_number', models.CharField(max_length=50, unique=True)),
                ('proof_file', models.FileField(upload_to='tenant_proofs/')),
                ('assigned_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_soft.room')),
            ],
        ),
        migrations.DeleteModel(
            name='One',
        ),
    ]
