# Generated by Django 5.1.6 on 2025-02-13 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0003_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
