# Generated by Django 5.1.6 on 2025-02-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0004_tenant_check_in_date_tenant_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='assigned_bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_soft.bed'),
        ),
    ]
