# Generated by Django 5.1.6 on 2025-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0007_alter_tenant_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='Other_proof_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
