# Generated by Django 5.1.6 on 2025-02-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0008_tenant_other_proof_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='Other_proof_name',
            new_name='other_proof_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=15),
        ),
    ]
