# Generated by Django 5.1.6 on 2025-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0009_rename_other_proof_name_tenant_other_proof_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='complaints',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
