# Generated by Django 5.1.6 on 2025-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0013_remove_tenant_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
