# Generated by Django 5.1.6 on 2025-02-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0014_tenant_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payment_amount',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
