# Generated by Django 5.1.6 on 2025-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0017_tenant_advance_amount_tenant_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='total_amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
