# Generated by Django 5.1.6 on 2025-02-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0018_tenant_total_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApartmentFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=10, unique=True)),
                ('flat_type', models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('3BHK', '3 BHK'), ('Studio', 'Studio')], max_length=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=15)),
                ('password', models.CharField(default='Pavan@123', max_length=255)),
                ('apartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_soft.apartment')),
            ],
        ),
    ]
