# Generated by Django 5.1.6 on 2025-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0019_alter_tenant_due_amount_alter_tenant_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentflat',
            name='flat_size',
            field=models.CharField(default='2550 sq.ft', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentflat',
            name='owner_email',
            field=models.EmailField(default='sai@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
