# Generated by Django 5.1.6 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0022_apartmentcomplaint_apartmentcomplaintreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentflat',
            name='flat_type',
        ),
        migrations.AddField(
            model_name='apartmentflat',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='flat_proofs/'),
        ),
        migrations.AddField(
            model_name='apartmentflat',
            name='purpose',
            field=models.CharField(choices=[('Rental', 'Rental'), ('Owned', 'Owned'), ('Other', 'Other')], default='Rental', max_length=10),
        ),
    ]
