# Generated by Django 5.1.6 on 2025-02-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0023_remove_apartmentflat_flat_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentflat',
            name='rent_amount',
        ),
    ]
