# Generated by Django 5.1.6 on 2025-02-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0024_remove_apartmentflat_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentflat',
            name='flat_type',
            field=models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('2.5BHK', '2.5 BHK'), ('3BHK', '3 BHK'), ('3.5BHK', '3.5 BHK'), ('4BHK', '4 BHK'), ('Studio', 'Studio')], default='1 BHK', max_length=10),
            preserve_default=False,
        ),
    ]
