# Generated by Django 5.1.6 on 2025-02-26 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0025_apartmentflat_flat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentcomplaint',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='apartmentcomplaintreply',
            name='created_at',
        ),
        migrations.AddField(
            model_name='apartmentcomplaint',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='admin_soft.apartmentflat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentcomplaintreply',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apartmentcomplaint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apartmentcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentcomplaintreply',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='admin_soft.apartmentcomplaint'),
        ),
        migrations.AlterField(
            model_name='apartmentcomplaintreply',
            name='sender',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
