# Generated by Django 5.1.6 on 2025-02-26 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0026_remove_apartmentcomplaint_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('solved', 'solved')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ApartmentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='admin_soft.apartment')),
            ],
        ),
    ]
