# Generated by Django 5.1.6 on 2025-02-27 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0027_alter_apartmentcomplaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAnnouncementReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='admin_soft.apartmentannouncement')),
            ],
        ),
    ]
