# Generated by Django 5.1.6 on 2025-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0028_apartmentannouncementreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentflat',
            name='role',
            field=models.CharField(default='owner', max_length=128),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='role',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
